//! Generates `common::paths` constants from the language-neutral SSOT `cores/common/paths.ini`
//! (build_env/paths-ssot). Only relative values are emitted; nothing absolute reaches the binary.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::PathBuf;

const MAX_KEYS: usize = 200;

fn main() {
    let ini = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("../../common/paths.ini");
    println!("cargo:rerun-if-changed={}", ini.display());
    let text = std::fs::read_to_string(&ini).unwrap_or_else(|e| panic!("read {}: {e}", ini.display()));

    let mut out = String::from("// @generated by common/build.rs from cores/common/paths.ini; do not edit.\n");
    let mut all = String::from("/// Every key with its section and raw relative value (tests compare against paths.ini).\npub const ALL: &[(&str, &str, &str)] = &[\n");
    let mut seen = BTreeSet::new();
    let mut section = String::new();
    for (n, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(name) = line.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
            section = name.to_string();
            continue;
        }
        let (key, value) = line.split_once('=').unwrap_or_else(|| panic!("paths.ini:{}: expected KEY=value", n + 1));
        let (key, value) = (key.trim(), value.trim());
        assert!(!section.is_empty(), "paths.ini:{}: key outside a section", n + 1);
        assert!(key.chars().all(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || c == '_'), "paths.ini:{}: key {key}", n + 1);
        assert!(seen.insert(key.to_string()), "paths.ini:{}: duplicate key {key}", n + 1);
        assert!(!value.is_empty() && !value.contains('\\') && !value.contains(':') && !value.starts_with('/'),
                "paths.ini:{}: {key} must be a relative '/' path", n + 1);
        writeln!(out, "/// `[{section}]` {key}\npub const {key}: &str = {value:?};").unwrap();
        writeln!(all, "    ({section:?}, {key:?}, {key}),").unwrap();
    }
    if seen.len() > MAX_KEYS {
        println!("cargo:warning=paths.ini has {} keys (> {MAX_KEYS}): revisit the structure (derive paths instead of listing)", seen.len());
    }
    all.push_str("];\n");
    out.push_str(&all);
    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("paths.rs");
    std::fs::write(dest, out).unwrap();
}
